

TEAMS = {'TAMPA BAY RAYS':'TBA',
 'MIAMI MARLINS':'MIA',
 'BOSTON RED SOX':'BOS',
 'LOS ANGELES ANGELS':'ANA',
 'OAKLAND ATHLETICS':'OAK',
 'TORONTO BLUE JAYS':'TOR',
 'TEXAS RANGERS':'TEX',
 'NEW YORK YANKEES':'NYA',
 'CHICAGO WHITE SOX':'CHA',
 'BALTIMORE ORIOLES':'BAL',
 'DETROIT TIGERS':'DET',
 'PHILADELPHIA PHILLIES':'PHI',
 'MILWAUKEE BREWERS':'MIL',
 'LOS ANGELES DODGERS':'LAN',
 'CINCINNATI REDS':'CIN',
 'CHICAGO CUBS':'CHN',
 'COLORADO ROCKIES':'COL',
 'CLEVELAND INDIANS':'CLE',
 'ST. LOUIS CARDINALS':'SLN',
 'KANSAS CITY ROYALS':'KCA',
 'MINNESOTA TWINS':'MIN',
 'SEATTLE MARINERS':'SEA',
 'SAN FRANCISCO GIANTS':'SFN',
 "ARIZONA D'BACKS":'ARI',
 'SAN DIEGO PADRES':'SDN',
 'WASHINGTON NATIONALS':'WAS',
 'PITTSBURGH PIRATES':'PIT',
 'NEW YORK METS':'NYN',
 'HOUSTON ASTROS':'HOU',
 'ATLANTA BRAVES':'ATL'}

LEAGUE = {'TBA':'AL',
         'MIA':'NL',
         'BOS':'AL',
         'ANA':'AL',
         'OAK':'AL',
         'TOR':'AL',
         'TEX':'AL',
         'NYA':'AL',
         'CHA':'AL',
         'BAL':'AL',
         'DET':'AL',
         'PHI':'NL',
         'MIL':'NL',
         'LAN':'NL',
         'CIN':'NL',
         'CHN':'NL',
         'COL':'NL',
         'CLE':'AL',
         'SLN':'NL',
         'KCA':'AL',
         'MIN':'AL',
         'SEA':'AL',
         'SFN':'NL',
         'ARI':'NL',
         'SDN':'NL',
         'WAS':'NL',
         'PIT':'NL',
         'NYN':'NL',
         'HOU':'AL',
         'ATL':'NL'}


TEAM_INITIALS = {'TBA':'TB',
                 'MIA':'MIA',
                 'BOS':'BOS',
                 'ANA':'LAA',
                 'OAK':'OAK',
                 'TOR':'TOR',
                 'TEX':'TEX',
                 'NYA':'NYY',
                 'CHA':'CHW',
                 'BAL':'BAL',
                 'DET':'DET',
                 'PHI':'PHI',
                 'MIL':'MIL',
                 'LAN':'LAD',
                 'CIN':'CIN',
                 'CHN':'CHC',
                 'COL':'COL',
                 'CLE':'CLE',
                 'SLN':'STL',
                 'KCA':'KC',
                 'MIN':'MIN',
                 'SEA':'SEA',
                 'SFN':'SF',
                 'ARI':'ARI',
                 'SDN':'SD',
                 'WAS':'WAS',
                 'PIT':'PIT',
                 'NYN':'NYM',
                 'HOU':'HOU',
                 'ATL':'ATL'}


PLAYERS = {
'Matt Koch': 'MATTHEW KOCH',
'Jonathan Gray': 'JON GRAY',
'C.C. Sabathia': 'CC SABATHIA',
'Matthew Andriese': 'MATT ANDRIESE',
'Shohei (H) Ohtani': 'SHOHEI OHTANI',
'AJ Pollock': 'A.J. Pollock',
'Daniel Vogelbach': 'Dan Vogelbach',
'Jonathan Gray': 'JON GRAY',
'JT Realmuto': 'J.T. Realmuto',
'Jacob Marisnick': 'Jake Marisnick',
'Joseph Wendle': 'Joey Wendle',
'Mike Marjama': 'Michael Marjama',
'Mike Tauchman': 'Michael Tauchman',
'Patrick Valaika': 'Pat Valaika',
'Thomas Pham': 'Tommy Pham'}


'''CHRISTIAN BERGMAN':
'MIKE SOROKA': 
'CLAY BUCHHOLZ':
'ARIEL JURADO':
'P.J. CONLON':
'SAM GAVIGLIO':}'''

TEAMS = {'TAMPA BAY RAYS':'TBA',
 'MIAMI MARLINS':'MIA',
 'BOSTON RED SOX':'BOS',
 'LOS ANGELES ANGELS':'ANA',
 'OAKLAND ATHLETICS':'OAK',
 'TORONTO BLUE JAYS':'TOR',
 'TEXAS RANGERS':'TEX',
 'NEW YORK YANKEES':'NYA',
 'CHICAGO WHITE SOX':'CHA',
 'BALTIMORE ORIOLES':'BAL',
 'DETROIT TIGERS':'DET',
 'PHILADELPHIA PHILLIES':'PHI',
 'MILWAUKEE BREWERS':'MIL',
 'LOS ANGELES DODGERS':'LAN',
 'CINCINNATI REDS':'CIN',
 'CHICAGO CUBS':'CHN',
 'COLORADO ROCKIES':'COL',
 'CLEVELAND INDIANS':'CLE',
 'ST. LOUIS CARDINALS':'SLN',
 'KANSAS CITY ROYALS':'KCA',
 'MINNESOTA TWINS':'MIN',
 'SEATTLE MARINERS':'SEA',
 'SAN FRANCISCO GIANTS':'SFN',
 "ARIZONA D'BACKS":'ARI',
 'SAN DIEGO PADRES':'SDN',
 'WASHINGTON NATIONALS':'WAS',
 'PITTSBURGH PIRATES':'PIT',
 'NEW YORK METS':'NYN',
 'HOUSTON ASTROS':'HOU',
 'ATLANTA BRAVES':'ATL'}

TEAMS_SHORT = {
'Indians': 'CLE',
'Yankees': 'NYA',
'Red Sox': 'BOS',
'Dodgers': 'LAN',
'Angels': 'ANA',
'Astros': 'HOU',
'Rays': 'TBA',
'Cardinals': 'SLN',
'Rockies': 'COL',
'Diamondbacks': 'ARI',
'Blue Jays': 'TOR',
'Giants': 'SFN',
'Cubs': 'CHN',
'Brewers': 'MIL',
'Royals': 'KCA',
'Phillies': 'PHI',
'Nationals': 'WAS',
'Pirates': 'PIT',
'Marlins': 'MIA',
'Mariners': 'SEA',
'Braves': 'ATL',
'Athletics': 'OAK',
'Twins': 'MIN',
'Orioles': 'BAL',
'Mets': 'NYN',
'Rangers': 'TEX',
'White Sox': 'CHA',
'Reds': 'CIN',
'Padres': 'SDN',
'Tigers': 'DET',
    }
    
    
pit_side_col_list = ['NAME',
 'HAND_pit',
 'G_SIDE_pit',
 'PA_SIDE_pit',
 'AB_SIDE_pit',
 'H_SIDE_pit',
 '1B_SIDE_pit',
 '2B_SIDE_pit',
 '3B_SIDE_pit',
 'HR_SIDE_pit',
 'TB_SIDE_pit',
 'SO_SIDE_pit',
 'BB_SIDE_pit',
 'HBP_SIDE_pit',
 'SF_SIDE_pit',
 'SH_SIDE_pit',
 'DP_SIDE_pit',
 'FB%_SIDE_pit',
 'GB%_SIDE_pit',
 'LD%_SIDE_pit',
 'POP%_SIDE_pit',
 'ISO_SIDE_pit',
 'AVG_SIDE_pit',
 'OBP_SIDE_pit',
 'SLG_SIDE_pit',
 'TAV_SIDE_pit',
 'DRA_SIDE_pit',
 'DRA-_SIDE_pit',
 'CFIP_SIDE_pit',
 'BASES_VS_AB_pit']


features_top_list = ['BASES_VS_AB_pit',
 'SLG_SIDE_pit',
 'AVG_batter',
 'def_LD%',
 'hit_mult',
 'SLG_batter',
 'pitcher_DRA',
 'DRA_SIDE_pit',
 'pitcher_FIP',
 'RBI_batter',
 'bat_OBP',
 'ISO_batter',
 'pitcher_BASES_VS_AB',
 'TAV_SIDE_pit',
 'def_H',
 'pitcher_PPF',
 'TB_SIDE_pit',
 'DP_batter',
 'bat_AVG',
 'bat_TAV',
 'def_GB%',
 'batter_BASES_VS_AB',
 'OBP_SIDE_pit',
 'SDTHB_BAT',
 'def_POP%',
 'pitcher_SO',
 'bat_SLG',
 'BASES_VS_AB_batter',
 'AVG_SIDE_pit',
 'SH_SIDE_pit',
 '3B_SIDE_pit',
 'H_SIDE_pit',
 'bat_ISO', 'TB_batter', 'SF_SIDE_pit', '1B_SIDE_pit',
 'R_batter', 'Rain', 'Temp', 'SO_SIDE_pit',
 'DP_SIDE_pit', 'GB%_batter', '2B_SIDE_pit', 'BB_SIDE_pit', 'POP%_SIDE_pit',
 'HBP_SIDE_pit',
 'SO_batter', 'FB%_batter', 'CFIP_SIDE_pit',
 'pitcher_ERA', 'POP%_batter', 'LD%_SIDE_pit',
 'GB%_SIDE_pit',
 'LD%_batter', 'HR_SIDE_pit', 'bat_RBI', 'FB%_SIDE_pit',
 'bat_SO', 'bat_FB%', 'bat_DP', 'Humidity', 'Expected_Runs',
 'bat_GB%', 'bat_POP%', 'bat_LD%']

g_df_away_cols = ['Date_Team', 'date', 'team_away', 'team_home', 'pitcher_home', 'expected_runs_away', 'actual_runs_away', 
                                       'temp', 'humidity', 'rain', 'league']
g_df_away_titles = ['Date_Team','Date', 'Team_Bat', 'Stadium', 'Team_Pitch', 'Expected_Runs', 'Runs', 'Temp', 
                                        'Humidity', 'Rain', 'League']








